name: psy-vtk
channels:
  - conda-forge
dependencies:
  - python=3.7
  - netcdf4
  - psy-simple>=1.3.0
  - jupyter
  - pip
  - pip:
    - git+git://github.com/pyvista/pyvista@master
    - ipyvtk-simple>=0.1.2
    - itkwidgets>=0.25.2
    - pyct
    - ..
